INSERT INTO CLIENT(ID, OS_USERNAME, SOCKET_PORT, IP_ADDRESS) VALUES(1, 'SHAYSINGH819', 345, '127.0.10.10');
INSERT INTO CLIENT(ID, OS_USERNAME, SOCKET_PORT, IP_ADDRESS) VALUES(2, 'SHAYSINGH820', 345, 'Testing1'); 
INSERT INTO CLIENT(ID, OS_USERNAME, SOCKET_PORT, IP_ADDRESS) VALUES(3, 'SHAYSINGH830', 345, 'Testing2'); 
INSERT INTO CLIENT(ID, OS_USERNAME, SOCKET_PORT, IP_ADDRESS) VALUES(4, 'SHAYSINGH814', 345, 'Testing3'); 
INSERT INTO CLIENT(ID, OS_USERNAME, SOCKET_PORT, IP_ADDRESS) VALUES(5, 'SHAYSINGH850', 345, 'Testing4');  
INSERT INTO CLIENT(ID, OS_USERNAME, SOCKET_PORT, IP_ADDRESS) VALUES(6, 'SHAYSINGH10', 345, 'Testing6'); 
INSERT INTO CLIENT(ID, OS_USERNAME, SOCKET_PORT, IP_ADDRESS) VALUES(7, 'SHAYSINGH818', 345, 'Testin7g'); 
