INSERT INTO CLIENT(ID, OS_USERNAME, SOCKET_PORT, IP_ADDRESS) VALUES(1, 'SHAYSINGH819', 345, 'Testing');

INSERT INTO CLIENT(ID, OS_USERNAME, SOCKET_PORT, IP_ADDRESS) VALUES(2, 'SHAYSINGH820', 345, 'Testing'); 
INSERT INTO CLIENT(ID, OS_USERNAME, SOCKET_PORT, IP_ADDRESS) VALUES(3, 'SHAYSINGH830', 345, 'Testing'); 
INSERT INTO CLIENT(ID, OS_USERNAME, SOCKET_PORT, IP_ADDRESS) VALUES(4, 'SHAYSINGH814', 345, 'Testing'); 
INSERT INTO CLIENT(ID, OS_USERNAME, SOCKET_PORT, IP_ADDRESS) VALUES(5, 'SHAYSINGH850', 345, 'Testing'); 
 
INSERT INTO CLIENT(ID, OS_USERNAME, SOCKET_PORT, IP_ADDRESS) VALUES(6, 'SHAYSINGH10', 345, 'Testing'); 
INSERT INTO CLIENT(ID, OS_USERNAME, SOCKET_PORT, IP_ADDRESS) VALUES(7, 'SHAYSINGH818', 345, 'Testing'); 
